server:
  port: 8084


spring:
      datasource:
        url: jdbc:mysql://127.0.0.1:3306/zgq?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: zhou
        driver-class-name: com.mysql.jdbc.Driver

mybatis:

  #  mybatis基于xml
  mapper-locations: classpath:/mapper/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.websocket.entity  # 注意：对应实体类的路径

  #打印sql语句，比较明显，效果好
  configuration:
    #    控制台打印出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启结果集自动映射（"_"——>驼峰命名）
    map-underscore-to-camel-case: true
